# Generated by Django 5.0.2 on 2024-09-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
